"""Legacy balance module — re-exports from :mod:`agent_society.economy.config`.

New code should import from `agent_society.economy` directly. This shim
exists only to keep long-established import paths working.
"""

from agent_society.economy.config import (
    BASE_VALUE,
    BASELINE_GOLD,
    DECAY_RATES,
    DESTRUCTION_FACTOR,
    GOLD_TAX_RATE,
    GOLD_TAX_THRESHOLD,
    HARVEST_BOOM_MULTIPLIER,
    HARVEST_FAILURE_MULTIPLIER,
    INFLATION_CAP,
    INFLATION_FLOOR,
    MERCHANT_INITIAL_GOLD,
    MERCHANT_MIN_MARGIN,
    NODE_INITIAL_GOLD,
    NORMAL_STOCKPILE,
    PLAGUE_PRODUCTIVITY_PENALTY,
    PRODUCE_WAGE,
    PRODUCER_INITIAL_GOLD,
    RAID_RATE,
    SCARCITY_K,
    STRENGTH_GAIN_FROM_SUCCESS,
    STRENGTH_LOSS_FROM_BASE_ATTACK,
    STRENGTH_LOSS_FROM_FAILURE,
    STRENGTH_STARVATION_DECAY,
    WEAPON_POWER,
)

__all__ = [
    "BASE_VALUE",
    "BASELINE_GOLD",
    "DECAY_RATES",
    "DESTRUCTION_FACTOR",
    "GOLD_TAX_RATE",
    "GOLD_TAX_THRESHOLD",
    "HARVEST_BOOM_MULTIPLIER",
    "HARVEST_FAILURE_MULTIPLIER",
    "INFLATION_CAP",
    "INFLATION_FLOOR",
    "MERCHANT_INITIAL_GOLD",
    "MERCHANT_MIN_MARGIN",
    "NODE_INITIAL_GOLD",
    "NORMAL_STOCKPILE",
    "PLAGUE_PRODUCTIVITY_PENALTY",
    "PRODUCE_WAGE",
    "PRODUCER_INITIAL_GOLD",
    "RAID_RATE",
    "SCARCITY_K",
    "STRENGTH_GAIN_FROM_SUCCESS",
    "STRENGTH_LOSS_FROM_BASE_ATTACK",
    "STRENGTH_LOSS_FROM_FAILURE",
    "STRENGTH_STARVATION_DECAY",
    "WEAPON_POWER",
]
